### ISSUE TITLE
Add examples of bad plots

### ISSUE THREAD

**Issue by j-emberton** [Cambridge-ICCS/summer-school-scientific-vis#19]
@jatkinson1000 

https://www.polymersearch.com/blog/10-good-and-bad-examples-of-data-visualization

Thinking of adding some examples pinched from this website to show good/bad plot implementations.

**Comment by jatkinson1000** [comment]
Good idea - bonus if we can use it to show how the plots can then be improved with skills from the session?
Not sure how easy that is though.
